### ISSUE TITLE
Request for UserScript assistance

### ISSUE THREAD

**Issue by dnmTX** [k08045kk/UserScripts#3]
Hi toshi @k08045kk 👋 ,first,let me say,already using the ServiceWorker UserScript and it works like charm. Great job 👍
I want it to ask if you can provide some assistance with another one of mine UserScript that i'm in a process of developing but my skills are very limited to say the least.
I'll wait for your response. If you're not up for it,or too busy,just simply close that issue.No harm done.
Thanks 👍

Also,when testing (UserScript was off and turned it back on after the service worker got registered) this is what i've noticed:
![internals](https://user-images.githubusercontent.com/34774426/122161523-7c5e2580-ce37-11eb-9422-11f8aa0c68ef.png)

STATUS showing that is RUNNING still. So,can you stop it alltogether or not possible?

**Comment by dnmTX** [comment]
Also this,when the script is running,and no worker was registered(all of it is from yahoo mail):
![yahoo](https://user-images.githubusercontent.com/34774426/122167578-cac3f200-ce40-11eb-86d7-d137e706d01a.PNG)

![yahoo1](https://user-images.githubusercontent.com/34774426/122167594-cdbee280-ce40-11eb-98cc-05cba1db8b5e.PNG)

**Comment by k08045kk** [comment]
[Question]
I recognized the problem as follows.
+ The problem occurred while using "RejectServiceWorker.user.js".
+ The target domain is "https://mail.yahoo,com/".
+ Accessed the above site with UserScript turned off, then turned it on and accessed the site again
  + When checked in Chrome's "chrome://serviceworker-internals/", the display was as shown in image 1 above
  + Recognized that "ServiceWorker had been installed".
+ Also, when I run the user script, it outputs the error messages in image 2 and image 3.


[Answer]
The second line of image 1 says "... (unregistered)" in the second line of Image 1. Therefore, the target ServiceWorker is considered to be in an unregistered state (unregistered). Therefore, it is assumed that the UserScript is working properly to unregister the ServiceWorker.

Please close the target page "https://mail.yahoo,com/". Then, the display of image 1 should disappear from "chrome://serviceworker-internals/".
(You may also need to update "chrome://serviceworker-internals/")


[Reason]
Image 1 is a Chrome specification.
It is thought that this is occurring because Chrome is displaying (explicitly) the ServiceWorker immediately after it is unregistered.

Image 2 and Image 3 are problems on the "https://mail.yahoo,com/" side. Or, it's a kind browser or "RejectServiceWorker.user.js" specification.
Uncaught (in promise) Error: ... is the error that is reported when Promise rejects but the catch handler is not set. RejectServiceWorker.user.js" returns a Reject to the registration function when rejecting a new ServiceWorker registration. However, "https://mail.yahoo,com/" does not set up a catch handler without considering the possibility of ServiceWorker registration failure, so the friendly browser is outputting an error.


<details>
<summary>Original text (Japanese)</summary>
<pre>
[質問]
以下のように問題を認識しました。
+ 「RejectServiceWorker.user.js」の使用中に問題が発生した
+ 対象ドメインは、「https://mail.yahoo,com/」である
+ UserScriptをオフの状態で上記サイトにアクセスして、その後オンにして再度サイトにアクセスした
  + Chromeの「chrome://serviceworker-internals/」で確認すると、上記の画像1の表示となった
  + 「ServiceWorkerがインストールされていた」と認識した
+ また、ユーザスクリプトを実行すると画像2、画像3のエラーメッセージを出力する


[回答]
画像1の2行目に「...(unregistered)」と記載されています。そのため、対象のServiceWorkerは、未登録状態（登録解除状態）であると考えられます。であるため、UserScriptは正常に動作してServiceWorkerを登録解除しているものと考えられます。

対象ページ「https://mail.yahoo,com/」を閉じてださい。そうすると、 "chrome://serviceworker-internals/" から画像1の表示が消えるはずです。
（"chrome://serviceworker-internals/" の更新が必要なこともあります）


[理由]
画像1は、Chromeの仕様です。
Chromeが登録解除直後のServiceWorkerを表示（明示）しているために発生しているものと考えられます。

画像2、画像3は、「https://mail.yahoo,com/」側の問題です。もしくは、親切なブラウザーか「RejectServiceWorker.user.js」の仕様です。
「Uncaught (in promise) Error: ...」は、PromiseがRejectしたがcatchハンドラーが設定されていない場合に通知されるエラーです。「RejectServiceWorker.user.js」は、ServiceWorkerの新規登録を拒否する際、登録関数に対してRejectを返します。ですが、「https://mail.yahoo,com/」は、ServiceWorkerの登録失敗の可能性を考慮せずにcatchハンドラーを設定していないため、親切なブラウザーがエラーを出力しています。


この回答であなたの問題が解決することを願っています。ありがとう。
</pre>
</details>

**Comment by dnmTX** [comment]
toshi @k08045kk thanks for the prompted answers. I think it answers all my concerns here,but i'm pretty sure that you rather such a thinks gets reported to you so you can keep some track. Your UserScript is working fine,i just...cause i don't want to have it run all the time and now trying to catch wich websites has Service Workers and then add htem to the script. Once they're added there are no visible errors showing. Anyway,good job,i like that you're passionate about it 👍 
Hey **toshi** if you're not too busy  can you take a look at this: 
https://chrome.google.com/webstore/detail/manage-web-workers/mcojhlgdkpgablplpcfgledhplllmnih  and see if you can make some simple UserScript,no options,just the basic blocking. It's very much abandoned and it might dissapear soon from the store.
And in a form of extension,it's very aggressive,even though i set it execute only on two websites,it's allways sits in the background,waisting memory and whatnot. I'm pretty sure that it's not very well coded.
Thanks again for your response here,i'll keep an eye on your repo in case you do some feature improvements to the script 👍

**Comment by dnmTX** [comment]
Oh...and to make a good suggestion here. Now that you hosting the script here can you include download and update links in the UserScript itself like:
`// @version .....`
`// @license .......`
`// @downloadURL ......`
`// @updateURL .....`
This way whenever you make any changes AdGuard will automatically check and update it on my end.
It's a good feature to have.

**Comment by dnmTX** [comment]
toshi @k08045kk i'm still testing,finding new targets to add and i figured out why when,after the fact all the caches are deleted and the SW is unregistered it's still remains in `chrome://serviceworker-internals/` with status RUNNING.
I simply have to klick on STOP and it's gone. So if you can figure out on your end how the script can make chrome to execute that(STOP) command,this will complete the whole process:

![serviceworker-internals](https://user-images.githubusercontent.com/34774426/122333276-85b1c580-cefd-11eb-99d2-a6668f23736f.png)

**Comment by k08045kk** [comment]
About 'Running Status: RUNNING'...

> Please close the target page "https://mail.yahoo,com/". Then, the display of image 1 should disappear from "chrome://serviceworker-internals/".
> (You may also need to update "chrome://serviceworker-internals/")

Did you use the quoted method and it did not solve the problem? Did you still see image 1 or image 4 in `chrome://serviceworker-internals/`?


---

About https://chrome.google.com/webstore/detail/manage-web-workers/mcojhlgdkpgablplpcfgledhplllmnih

It is possible to provide a function to reject Worker (WebWorker and SharedWorker) as a user script. However, it will not be provided as an additional function of "RejectServiceWorker.user.js". This is because rejecting Worker (WebWorker and SharedWorker) and rejecting ServiceWorker are completely different functions.


---

Automatic updating of user scripts

The "RejectServiceWorker.user.js" user script was created with the assumption that the metadata section (`@include` or `@exclude` or `@match`) can be modified by the user. Therefore, in order to prevent overwriting the user script by updating it, the user script update function is not used.


---

Please do not develop multiple topics in one Issue. It makes for very difficult reading.

**Comment by dnmTX** [comment]
> Did you use the quoted method and it did not solve the problem? Did you still see image 1 or image 4 in chrome://serviceworker-internals/?

I didn't the first time,then i did and my suggestion here was if you can automate this in your script(instead of me clicking on it). That's all.

> It is possible to provide a function to reject Worker (WebWorker and SharedWorker) as a user script. However, it will not be provided as an additional function of "RejectServiceWorker.user.js". This is because rejecting Worker (WebWorker and SharedWorker) and rejecting ServiceWorker are completely different functions.

I actually meant for you to reverse engeener that extension and create completely different UserScript to block and delete 
Dedicated Workers or so called Web Workers. Judging by your skills it shouldn't be a big deal for you.
Again,that extension is abandoned for a long time and not maintained,but it's still works though.
You can do it man. C'mon 🚀 

> Automatic updating of user scripts
The "RejectServiceWorker.user.js" user script was created with the assumption that the metadata section (@include or @exclude or @match) can be modified by the user. Therefore, in order to prevent overwriting the user script by updating it, the user script update function is not used.

Yeah,i figured that part eventually and even deleted that question,the best thing in situation where customisation is required is
to implement the **RELEASE** feature here in your repo,and every time when you make changes,just release it with higher version.This way,anyone who is subscribed here will recieve notification.Like this:
![release](https://user-images.githubusercontent.com/34774426/122487662-640a1a00-cfa1-11eb-8c52-16ebdf7b952f.png)

> Please do not develop multiple topics in one Issue. It makes for very difficult reading.


Sure thing,sorry about that 👍

**Comment by k08045kk** [comment]
> I didn't the first time,then i did and my suggestion here was if you can automate this in your script(instead of me clicking on it). That's all.

There is no need to automate. You can completely uninstall ServiceWorker by refreshing the page or by closing the page. I don't understand the need to manually (or automate) pressing the STOP button.

---

I don't need the ability to stop the Worker from running. But you do need it. If I could create it, what would you offer me in exchange for the time it would take me to create it? (I've already consumed decades of time to get this technology)

---

If you are using the release feature, this form of repository that contains all user scripts is problematic. It may be necessary to separate all user scripts into separate repositories. We will consider this.

**Comment by dnmTX** [comment]
> I don't need the ability to stop the Worker from running. But you do need it. If I could create it, what would you offer me in exchange for the time it would take me to create it? (I've already consumed decades of time to get this technology)

Hey...this is GitHub,where capable coders create and share their work with the **WORLD** ( 👈  you got that? )
You want to make money,open your own website and sell,the question is who will buy it.
Or better yet.....go sell your ass on the market,i bet you'll make a fortune ❗  👈 

> (I've already consumed decades of time to get this technology)

Decades????????  Who the fuck you think i am?  Your stupid 20 lines script is far from....**technology**
I just need to google-it and will find much much better once.  Wake UP  !!!!!!!

Now PISS OFF and most importantly  **ふざけるな君はばかやろう**

**Comment by k08045kk** [comment]
I post my work on GitHub. But I don't want to make work that I don't want to make, and I don't think I can support that work for a long time. You're asking me to make work that I don't want to make. You have refused to provide a market in exchange. "Do you refuse non-market compensation?" The conversation is already over. It's a pity.

Ask Google a question, and you will get what you seek. The answers are already in place. I hope you won't misbutton your clothes next time. See you.
